### ISSUE TITLE
[bug] `appcenter codepush promote` seems to disregard `--target-binary-version`

### ISSUE THREAD

**Issue by nmutalik** [microsoft/appcenter-cli#1179]
In our codepush setup we have two deployments, `Staging` and `Production`. As of right now, the latest version of our Production app is 1.38, however we have some 1.39 builds on Staging.

Earlier today I ran

```bash
appcenter codepush promote
	--source-deployment-name Staging
	--destination-deployment-name Production
	--target-binary-version '~1.38'
```
I expected it to take the latest 1.38 build on Staging and promote it to Production. Instead, it took the latest build irrespective of version (1.39) and promoted that to Production. Unsurprisingly this broke things.

I'm not sure if this is expected behavior, at least it doesn't seem to be documented that way. If it is, please let me know.

Also, I'm not certain, but it looks like if this is a bug, it might be a backend bug. If so, and there's a better place for me to report this issue, let me know.

**Comment by Shaddix** [comment]
I'd plus one this issue.
In other words, for us it'd be nice to have a way to identify what build I want to promote. Currently we could identify the build to promote by `label` parameter, but I don't see a way to change or even get the label.

My scenario: I have a CI pipeline in Azure DevOps which runs `appcenter release-react` to Staging. Later (as a manual step in the pipeline) I'd want to promote the release to Production.
At this point (could be several days later, so the release isn't already the last one in Staging) I don't know how to identify this CodePush release. I don't know what it `label` was (or don't know how to get it).
Promoting by `target-binary-version` would actually solve the issue for me.
Another solution would be an ability to change the `label` via e.g. `appcenter codepush patch`, so that I could initially set the known label and then promote it by label.

**Comment by AnatolyPristensky** [comment]
Hello @Shaddix, and thank you for getting in touch with us!
We will discuss it with a team and update this thread once get results.

**Comment by AnatolyPristensky** [comment]
@Shaddix, we created a bug on our internal dashboard. Will update this thread once bug will fixed.

**Comment by AnatolyPristensky** [comment]
Hello, @Shaddix ,
Appropriate team confirmed that fix has been published to the prod and now the issue should be resolved.
Please, feel free reopen this issue if you still facing this bug.

**Comment by nhannah** [comment]
@AnatolyPristensky I am not sure if this is related but we just had what seems like a regression in how promote works? On Jan 10 I made a code push to Staging, then promoted it. On Jan 27 I did the same, I noticed an odd issue on Jan 27, it said my bundles were the same, so I figured it was an error and went and hand promoted the build. On Jan 31 I did this a 3rd time, no issue this time, but today Feb 1 I realized the Jan 10 bundle was promoted back to prod, not the new Jan 31 bundle. These all targeted the same version. This seems like a rather bad issue as promote is promoting the OLDEST not NEWEST build of that version target.
