### ISSUE TITLE
Exclude *.map files from package to reduce size (5mb => 1.4mb)

### ISSUE THREAD

**Issue by retyui** [microsoft/appcenter-cli#1451]
**Is your feature request related to a problem? Please describe.**

I use the next command to bandle package and deploy it to AppCenter

```sh
npx appcenter codepush release-react --app "my.user/MyApp-Android" \
   --deployment-name "test" \
   --sourcemap-output \ # https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#source-map-output-parameter
   --output-dir "./build-android"
```

I use `--sourcemap-output` to upload "*.map" files to my error tracking service (Sentry: https://docs.sentry.io/platforms/react-native/manual-setup/codepush/)

But a package is increased 3 times ( and this new size is compressed .map file) 

**Describe the solution you'd like**

prevent add debug files into package from the box

**Describe alternatives you've considered**

**Additional context**

**Comment by retyui** [comment]
Now the only way to exclude source-maps (as a workaround) is to define source-maps output to tmp folder:

- `--sourcemap-output "/tmp"`
- `--sourcemap-output-dir "/tmp"`

**Comment by alexandergoncharov** [comment]
Hi there,

Thanks for reporting and also providing a workaround for this.

Unfortunately, the AppCenter project is in maintenance mode now where will not be added new features and increasing functionality.
Here is more info: https://github.com/microsoft/appcenter#planning

So, we are going to keep your issue here and consider it when we finish maintenance mode.

Please, feel free to ask any questions :)

Thanks,
Alexander
