### ISSUE TITLE
"Could not find Info.plist" error when uploading macOS pkg zip file.

### ISSUE THREAD

**Issue by naga-cf** [microsoft/appcenter-cli#1682]
### **Description**
Please describe the issue you are facing using the CLI.
We are building our macOS application using Azure Devops and use appcenter-cli in a bash script to upload pkg installer file zipped in a zip file. We haven't had any problems with this workflow for about a year but our upload step is failing starting from Oct 5th 2021 with error "Could not find Info.plist (Correlation ID: xxxxx)". 

We don't really understand the error since we do not ship Info.plist either in zip file or in the pkg file.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Upload zip file which contains macOS pkg installer using appcenter-cli or from UI.
2. Upload fails with "Could not find Info.plist (Correlation ID: 93268a3d-db8d-4e2f-9dc8-d30f6108aca7)"

### **Expected behavior**
Upload succeeds.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    `appcenter distribute release --app`
2. Which version of the App Center CLI are you using?
    2.10.2
3. Which OS version did you experience the issue on?
    macOS BigSur 11.1
4. What command line/shell are you using?
    Shell 5.8 
5. What version of Node.js and NPM/Yarn are you using?
    
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.
`- Checking the uploaded file...  appcenter-cli:commands:distribute:release Received release id is undefined +400ms
Release upload failed
Error: Loading release id failed: Could not find Info.plist (Correlation ID: 295a28ba-d48d-4306-96f6-6b998ed4d6c4)
`

**Comment by DmitriyKirakosyan** [comment]
Since you have the same issue when uploading via web portal, it is not an `appcenter-cli` issue.

Please open a support ticket by navigating `appcenter.ms -> ? (question mark, upper right corner) -> Contact support`.
You can share your app information in the private chat with the App Center support team and the backend team will be able to investigate your problem by checking the logs from your app.

I'm closing this issue, but feel free to reopen if you have additional questions.
