### ISSUE TITLE
AppCenter test - Devices selection within concurrent devices amount

### ISSUE THREAD

**Issue by Naweap** [microsoft/appcenter-cli#1888]
Dear support/community,

I went for an AppCenter subscription of 4 concurrent devices.

Actually, I've different test runs in my case and I would like to know if it's possible to split a bit the execution.

My scenario is the following :

- One test run where I would like to execute on one device only
- One test run where I would like to execute on one device only
- One test run where I would like to execute on four devices

I tried to create multiple devices sets with only one device inside. But if I'm running the second test run it will still wait until the first one finish even if I've a total of four concurrent devices and I've configured a different device type in my set.

What I want to have is to be able to run multiple test run in parallel without using all my concurrent devices available. Is this possible and how should I do ?

Hope I've been clean in my explanations.

Thanks in advance

**Comment by DmitriyKirakosyan** [comment]
Hi @Naweap , thank you for getting in touch with us!

Please, [contact our support team](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) using the question mark on the appcenter.ms portal. They will help you with these questions.

Since it is not related to the AppCenter CLI, I'm closing this issue. Please let me know if you have additional questions.
