### ISSUE TITLE
Codepush. React Native. Private key is not applied

### ISSUE THREAD

**Issue by o-alexandrov** [microsoft/appcenter-cli#1889]
### **Description**

When releasing a new codepush update for React Native, private key is not applied.
The exact same procedure worked for `Cordova`, which is retired.

### **Repro Steps**

1. Run `appcenter codepush release -k ./private-ios.pem -a name -c www -m`
2. Examine the `.zip` file, it doesn't contain the signature

### **Expected behavior**

When publishing for React Native with a private key, the signature is attached to the update as it does for `Cordova`.

### **Details**

This issue is described in detail here https://github.com/mapiacompany/capacitor-codepush/issues/64.
It was fixed by this commit in a fork https://github.com/bazuka5801/appcenter-cli/commit/1520f80181d67588d8ca24392ef92cf4e8f7ca52

**Comment by AnatolyPristensky** [comment]
Hello @o-alexandrov and thank you for getting in touch with us!
We filed an item on our internal dashboard to check this case.
Will update this thread once get results.

**Comment by AnatolyPristensky** [comment]
Hello @o-alexandrov, I've tested your case by performing the following steps:
1. `npx react-native bundle --entry-file index.js --bundle-output ./www/main.jsbundle`
2. `appcenter codepush release -k key.pem -c www -t 1.0`
3. Checked downloaded archive from AppCenter portal and found that the file `.codepushrelease` exists inside the .zip archive. 

Could you please share more information on how you could reproduce this issue? 

Also, please note that it's recommended to use `release-react` command instead of `release` command.

**Comment by AnatolyPristensky** [comment]
We haven't heard from you for a while, so I'm closing this issue. 
Please, feel free to reopen it in case of new information.
