### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by princeSmall** [microsoft/appcenter-cli#2463]
npm config ls                                          
; "builtin" config from /opt/homebrew/lib/node_modules/npm/npmrc

prefix = "/opt/homebrew" 

; "global" config from /opt/homebrew/etc/npmrc

; strict-ssl = false ; overridden by user

; "user" config from /Users/letong/.npmrc

ca = [""] 
NODE_TLS_REJECT_UNAUTHORIZED = "0" 
registry = "https://registry.npm.taobao.org" 
strict-ssl = false 

; node bin location = /opt/homebrew/Cellar/node/20.5.1/bin/node
; node version = v20.5.1
; npm local prefix = /Users/letong
; npm version = 9.8.0
; cwd = /Users/letong
; HOME = /Users/letong
; Run `npm config ls -l` to show all defaults.

**Comment by AnatolyPristensky** [comment]
Hello @princeSmall, I suppose that you're getting this error during login via appcenter-cli. I've tried to reproduce your case but everything works as expected for me, so the issue is on your local environment side. 

It could happens due to the following reasons:
1. You're behind a proxy, if so, ensure it's set up correctly.
2. You're using a VPN, try disconnecting and reconnecting or try without it.
3. The registry is set to https://registry.npm.taobao.org, try to use the official npm registry instead.
