### ISSUE TITLE
distribute release; should output the ID of the release

### ISSUE THREAD

**Issue by gustafnilklint** [microsoft/appcenter-cli#2484]
### **Description**
After distributing a release to AppCenter one might need to be able to refer to this specific release.
In previos version of appcenter-cli you could use **--debug** and then parse out the id from the output.

Ideally the id of the release should be returned on separately.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. npx appcenter distribute release --token *** --app user/appName --file build/app.ipa --group TESTERS --release-notes 'Changes' --silent --debug

### **Expected behavior**
Somewhere in the output I'd expect to find the ID of this release.
The ID is what is unique in direct links to install this release: 
h t t p s : / / install.appcenter.ms/users/username/apps/appname/releases/**1234**

### **Details**
As I mentioned, this was possible in version 2.x.x of the cli by specifying --debug flag.
In version 3, debug flag does not output anything similar. Ideally a separate flag could make this even more convenient by returning the ID without all the noise produced by --debug flag

**Comment by DordeDimitrijev** [comment]
Hello [@gustafnilklint](https://github.com/gustafnilklint) thank you for reaching out. In order to extract specific logs like those including release id please enable debug logs with environment variable like stated [here](https://github.com/microsoft/appcenter-cli/blob/master/contributing.md#enabling-debug-logs).
For example the command you are trying to use would look like

```
DEBUG="appcenter-cli:commands:distribute:release"
appcenter release --token *** --app user/appName --file build/app.ipa --group TESTERS --release-notes 'Changes'
```
Let me know if you were able to extract the needed information from the output.

**Comment by DmitriyKirakosyan** [comment]
Closing. @gustafnilklint please let us know if you are still facing the issue.
