### ISSUE TITLE
Appcenter distribute release hitting timeout

### ISSUE THREAD

**Issue by foonjs** [microsoft/appcenter-cli#2545]
### **Description**
Please describe the issue you are facing using the CLI.
I have tried to use "appcenter distribute release" command to distribute a package to my targeted appcenter app.

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. appcenter distribute release --app `<app name>` --file `<path to file>` --group `<group name>`

### **Expected behavior**
The command should be able to distribute with no error/timeout.

Getting this error message instead:
`failed, reason: connect ETIMEDOUT 13.107.246.59:443`

and the status of this proxy seems to be down at the moment.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
   - appcenter distribute release
2. Which version of the App Center CLI are you using?
    - 3.0.0
3. Which OS version did you experience the issue on?
    - e.g. macOS Sonoma 14.4.1 (23E224)
4. What command line/shell are you using?
    - Terminal Version 2.14 (453) /bin/bash
5. What version of Node.js and NPM/Yarn are you using?
    - e.g. node v20.12.2, npm 10.0.0

**Comment by DordeDimitrijev** [comment]
Hello @foonjs  thank you for reaching out. Could you please share additional logs  using debug env variable like explained [here](https://github.com/microsoft/appcenter-cli/blob/master/contributing.md#enabling-debug-logs)?  Also Are you using proxy to distribute release if so did you configure it properly. In order to use it you would need to call the command like this `HTTPS_PROXY="http://%proxy.username%:%proxy.password%@%proxy.hostname%:%proxy.port%" appcenter distribute release...` ?

**Comment by foonjs** [comment]
Hi @DordeDimitrijev ,

Thanks for the tip. It seems to be working after I added the HTTPS_PROXY configuration. I wasn't aware of this proxy setting. Anyways, I will be closing this thread.
