### ISSUE TITLE
Codepush: Get failed sync error details

### ISSUE THREAD

**Issue by saifeer** [Microsoft/appcenter-cli#370]
Hi,.

As of now, when the sync method is called and the SyncStatus get an ERROR value, there is no way to get the actual error. The documentation states the error details are in the console log but in live production, there should be a way to get the error details in the SyncCallback as an argument so they can be used for troubleshooting (like for eg. sending them out as error report to developers).

Thanks!

**Comment by max-mironov** [comment]
Hello @saifeer and thank you for your question. 
It looks like your question relates more to https://github.com/Microsoft/react-native-code-push SDK itself rather than the CLI, so probably you could ask more questions here. 
But I'd like to notice that adding better crashes support is in our roadmap, some more details could be picked up from this thread: https://github.com/Microsoft/react-native-code-push/issues/1099

**Comment by saifeer** [comment]
Hi @max-mironov,

Yes you are absolutely right! Apologies for the incorrect filing. I have opened an issue for the Cordova SDK Repo now.
Closing this issue now.
