### ISSUE TITLE
Unable to Login. Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by fufu70** [Microsoft/appcenter-cli#395]
Currently running the latest build, `1.0.11`

When I try to login and enter in the `Access code from the browser: ` hash, that I receive after logging in to the appcenter webapp, I get an error:

`Error: unable to get local issuer certificate`

I'm behind a corporate firewall and my .npmrc file contains the following:
```
NODE_TLS_REJECT_UNAUTHORIZED=0
registry=http://registry.npmjs.org/
strict-ssl=false
ca=
```

**Comment by amchew** [comment]
Hi @fufu70 , thanks for letting us know. We're working to investigate this, and will update again.

**Comment by christav** [comment]
@fufu70 Took a look, and I'm unable to reproduce this.

Your .npmrc settings are not used for this. only for npm, so that doesn't have any bearing on the issue.

Could you try to set an environment variable for https according to here: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables and let us know if that fixes your issue?

**Comment by amchew** [comment]
Hey @fufu70 /Christian, we haven't heard back from you in some time, and I'll be closing this ticket for now. Please reach back again if you have questions anytime, and we'll reopen this ticket again.

Thank you for your support!
Amanda

**Comment by sebastianferrari** [comment]
The following set worked for us:
`NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by amchew** [comment]
Hey @fufu70, hope you’re well! Quick check, it seems like your issue was resolved. Would you mind sharing what steps you took to resolve it?

**Comment by princeSmall** [comment]
Error: unable to get local issuer certificate

**Comment by privatepej** [comment]
Facing the same issue.  any solution ?
