### ISSUE TITLE
login fails on non interactive login

### ISSUE THREAD

**Issue by john7doe** [Microsoft/appcenter-cli#417]
appcenter-cli login -u <user> -p <token> fails if the first invocation is from a non interactive shell.

src/util/token-store/file/file-token-store.ts assumes that .appcenter-cli dir exists. It does not exists unless the user has been prompted for telemetry, which does not happen if the shell is not interactive.

**Comment by christav** [comment]
Interesting - sounds like a bug, I'll take a look.

I would like to ask what scenario you're trying to do the login in a non-interactive shell? Are you trying to do a login from a CI server? If that's the case, you shouldn't log in (since that sets machine-user state), and instead use an api token. There are two options there:

  1. Set the APPCENTER_API_TOKEN environment variable to your api token, and then it should just work.
  2. add the `--token <your api token here>` switch to each of your commands.

If that's not the scenario you're running, I'd love to know what it is so I can make it easier.

**Comment by christav** [comment]
Should be fixed in release 1.0.14, which just went out. Please reopen if it reoccurs.

**Comment by amchew** [comment]
Super fast work, thanks @christav !
