### ISSUE TITLE
Build fails when runs from API

### ISSUE THREAD

**Issue by BehradI** [Microsoft/appcenter-cli#494]
when Build starts either from New Commit or manual build, there is no issue.
Spuriously when  trigger the build from Appcenter API (/v0.1/apps/{owner_name}/{app_name}/branches/{branch}/builds)
build fails, 

attachment is the log when run the build from API 

[log.log](https://github.com/Microsoft/appcenter-cli/files/2476460/log.log)

**Comment by amchew** [comment]
Hi @BehradI , this seems to be an issue with the API instead of the CLI (correct me if I'm wrong). Could you go to https://appcenter.ms, log in to App Center, click the blue conversation button at the bottom right corner of the page, and start a conversation there? Feel free to paste this ticket there, and mentioned to be transferred to Amanda Chew, I'll channel this to the right team. Thank you.

**Comment by amchew** [comment]
Hey @BehradI, did you manage to log a ticket in App Center? Alternatively, please email me amchew [at] microsoft.com your App Center log in email, and I can start a ticket there.

**Comment by amchew** [comment]
Hi @BehradI, I haven't heard back from you, and will be proceeding to close this conversation. Feel free to re-open this/re-comment here if you have any other questions!
