### ISSUE TITLE
Command to generate Android NDK symbols.zip file

### ISSUE THREAD

**Issue by sseyod** [microsoft/appcenter-cli#601]
Hi! Is there any reason why appcenter-cli doesn't contain a simple command to do the building of symbols.zip automatically, c.f the complex steps described here...:

https://docs.microsoft.com/en-us/appcenter/diagnostics/android-ndk

Suggestion: create symbols.zip that covers all the so files in the distribution:

appcenter crashes make-ndk-symbols-zip

**Comment by jpeg-ms** [comment]
Hi @sseyod,
There is a reason indeed, and it is because the tool used to extract the symbols only works on Linux. As you already know, I prepared a Docker-based tool to do the job, available at https://github.com/microsoft/appcenter-cli/issues/618.
I marked this as a feature-request as we could integrate a solution within the CLI.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue
