### ISSUE TITLE
Support 'notify_testers' parameter

### ISSUE THREAD

**Issue by ddovod** [microsoft/appcenter-cli#602]
Hello guys. Thank you very much for this tool!
Could you please consider exposing `notify_testers` argument so we can roll out silent releases and not spam people with useless emails? Afaik it is already implemented and used, but not exposed in the cli.
Thanks in advance!

**Comment by dbquarrel** [comment]
This, this so much. This. 

I wrote a workaround for the missing functionality. What you need to do is:

1. create a new distribution group with the CLI or the website, call it "Empty" and don't add anyone to it. You will use this Empty group as your target for uploads.

2. You do a release to this group, and then have to immediately ask for the list of releases since the CLI gives you no feedback about the release number you just made (this is another shortcoming of their design). So this is not failsafe if multiple people are doing releases but for a solo worker it is OK.

3. You then use add-destination with the silent options, and it should work. I've had users complain that nothing happened at all. But I've tested on my end and I've seen it work. The whole thing seems rather flaky.

    distgroup=All-users-of-Yourapp
    UPLOAD_NOTES=your_notes_file.txt
    IPA=your.ipa
    XCARCHIVE=your.xcarchive
    appcenter distribute release -g Empty -R "${UPLOAD_NOTES}" -f "${IPA}"
    version=`appcenter distribute releases list | head -1 | awk -F: ' {print $2} '`
    appcenter distribute releases add-destination -d ${distgroup} --silent --mandatory --type group -r ${version}
    appcenter crashes upload-symbols --xcarchive "${XCARCHIVE}"


1. we need to be able to tailor the notification settings on an upload so that this kind of hackery is not necessary
2. we need the release number to be put on stdout after the release is uploaded as part of the confirmation to help us enable this kind of thing in a script rather than interactively using grep and eyeballs and typing.

**Comment by hari331996** [comment]
> 3\. Empty

I am not able to release to an empty group as shown in your command. Can you help me?
