### ISSUE TITLE
What's the rationale behind v2.0.0?

### ISSUE THREAD

**Issue by MihaMarkic** [microsoft/appcenter-cli#624]
The description for version 2.0.0 is really scarce. Can anybody comment on what changed command wise?

**Comment by owenniblock** [comment]
Release 2.0.0 is basically [Release 1.2.1](https://github.com/microsoft/appcenter-cli/releases/tag/v1.2.1) but with a major version bump.

We had some feedback from users that the node upgrade (8 -> 10) cause CI failures and some confusion as it was only marked as a minor version update.

Because of this we rolled back the 1.2.x release to before the node 10 upgrade and reapplied that as 2.0.0 - this way there are no breaking changes on 1.2.x - only on 2.x

Hope that makes sense. Basically, if you want node 10.x developed code and any future update, use 2.x

**Comment by MihaMarkic** [comment]
A, ok then. So no command line changes then. Thanks.

**Comment by l3ender** [comment]
Might I suggest a changelog file in the repo to help people understand the versions better? I also was not sure on the 2.0.0 version.

**Comment by owenniblock** [comment]
@amchew adds changelog changes here: https://docs.microsoft.com/en-us/appcenter/general/changelog - although I think it has missed the last few changes.

@l3ender - I'll discuss with Amanda about moving the changelog notes in to the repo instead.
