### ISSUE TITLE
Failed to release a CodePush update on Windows

### ISSUE THREAD

**Issue by StebanDev** [microsoft/appcenter-cli#638]
I was trying to release an update with Hermes enabled using appcenter-cli version 2.1.1 on Windows but i'm getting the following error:

![image](https://user-images.githubusercontent.com/13490436/64071784-47bfb080-cc47-11e9-820a-9aafbb214878.png)

This issue only occurs on Windows native console, I have tested it out on Linux and WSL and got it working.

**Comment by brerdem** [comment]
Hey @StebanDev ! I think the problem is hermesvm itself. It simply doesn't produce an output. I visited its NPM page and it says hermesvm name will be depreceted and it will continue under the name hermes-engine. Maybe we can download hermes separately and try to convert the build by ourselves. I will update you if I can succeed or not.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this issue in the next year, I'm closing the issue.
