### ISSUE TITLE
Do you know what id I should specify in appcenter build download command?

### ISSUE THREAD

**Issue by waynemd** [microsoft/appcenter-cli#672]
Is there more detail parameter sample to see how this command work?

```$ appcenter build download
Error: Command 'build download' failed with exception "Missing required option -i / --id"```

**Comment by jerietve** [comment]
Hi @waynemd. The documentation/examples are limited for the moment. I will give you a writeup of how to use it here.

The `build download` command its `-i` or `--id` parameter is required, which you can see in the usage when you run `help build download` because the parameter is not surrounded by [brackets]. The value you should provide is the ID number of a build of the app for which you want to download something. The app you must specify using the `-a` parameter, and the thing you want to download (the build binary, logs or symbols) you must specify using the `-t` parameter.

To find the IDs for older builds, sign in to the App Center portal and go to your app > **Build** > 
your branch, to see the list and the IDs.

There is currently no good way to find the build ID using the CLI. If you run `build branches list`, you will see the overview of the branches which are configured for build. For each branch you will see the latest build ID, and the build result. If the result is `failed`, you can't download the build but you can still download the logs.

To give an explicit example, if you wish to download the latest successful `build file` for your app `MyApp`, you could first run:

`appcenter build branches list --app MyApp`

Or, if you know the branch and it is called let's say `master`:

`appcenter build branches show --app MyApp --branch master`

This gets you the latest build ID. If it succeeded, use this build ID. If it failed, sign in to App Center through the website to get the build ID for the latest successful one. Then with that build ID, say `17`, run:

`appcenter build download --app MyApp --type build --id 17`

This will download the build file to your current directory. Use the `--dest` parameter to specify the download folder and `--file` to specify the file name.

Please let me know if you have any further questions. While we have you here, I would like to ask you something. Where would you expect to find the more detailed examples like the one you asked for in this ticket?

**Comment by waynemd** [comment]
Thanks for the detail writeup.

One more question with this download command
`appcenter distribute groups download -g <group> -a <app>`
Does it only download the LATEST version of the release package for the distribution group?

`appcenter distribute groups show -g <group> -a <app>`
shows all the users and releases.

**Comment by jerietve** [comment]
The command `distribute groups download` downloads the latest release, unless you specify which release you want by using the `--id` parameter.
