### ISSUE TITLE
How to set an app to a unrelated group?

### ISSUE THREAD

**Issue by liszto** [microsoft/appcenter-cli#673]
Hello,
I'm facing an issue that wasn't there last week (which is odd...).
I had to setup an **Empty group** in the AppCenter dashboard to allow us to release our app without any group in entry. I made an issue on this to allow dev to upload release without specified any group (but it's not the subject here).

But this Empty group doesn't contain any apps and last week I could use this command line : 
`appcenter distribute release --silent --token "$APITOKEN" -a "$OWNERNAME/$APPNAME" -g "Empty" -r "$RELEASENOTES" -f "$BUILDPATH"`
and everything was fine.

But today I tried this one on an app not contained by the "Empty" group which is normal because I set nothing in the AppCenter dashboard and the command failed with the error : 
`Error: Could not find group Empty`

So I have some questions : 
- Why could I do this previous week but not anymore now ? 
- Could it be possible to do it again ? (because it's useful to do this as soon as the group is possessed by the organization specified in the "$OWNERNAME" variable)
- Is it possible to add app through appcenter-cli command ? (if it's not, that's mean we need a human action and it's not possible in a CI logic)

Thanks.

**Comment by Ajaykn21** [comment]
Hi @liszto 
AppCenter has groups concept in two ways.
1) You can create a group at App level and releases can be distributed to that group
2) You can create a group at Org level and can add apps to that group, so that releases can be distributed to that group.
For more info: please go through this.
https://docs.microsoft.com/en-us/appcenter/distribution/groups

Now I assume, `Empty` group is at app level and so first app you tried has worked and the second app you were trying failed.

> Is it possible to add app through appcenter-cli command?
yes, app creation is supported. Please check 
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/40024974/66553761-ac472700-eb86-11e9-804e-ef6c3e9e6cad.png">

Hope this answers your questions.

**Comment by liszto** [comment]
That's not really what I asked.
First of all how can I create a group with appcenter-cli for an organization and add apps to it ?

If I can do this I think I can handle it myself.

When I asked : 
`Is it possible to add app through appcenter-cli command?`

I would say : is it possible **to add app to a group through appcenter-cli** not just add an app.

**Comment by Ajaykn21** [comment]
@liszto Currently, creating the group in organization and adding the app to a group is not supported through CLI.

Tagging this feature-request and we will prioritize accordingly

**Comment by DmitriyKirakosyan** [comment]
Hi @JonnyPtn , unfortunately we don't have ETA for this feature. Please use open API as a workaround.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
