### ISSUE TITLE
Add option to specify "dsa_signature" metadata for distribute release

### ISSUE THREAD

**Issue by triplef** [microsoft/appcenter-cli#730]
Please add an option to specify the `dsa_signature` metadata when using the `distribute release` command. This parameter is available on the [update releases endpoint](https://openapi.appcenter.ms/#/distribute/releases_update).

The parameter is required when using App Center to distribute macOS and Windows app updates via Sparkle, and currently requires manually calling the endpoint:
https://docs.microsoft.com/en-us/appcenter/distribution/sparkleupdates#specify-the-dsa_signature-via-api

**Comment by ahdbilal** [comment]
Thanks for the feedback. This has been added to feature backlog.

**Comment by tonyarnold** [comment]
Can this request please be updated to allow the `ed_signature` field as well? 

It would be nice if these could be specified as parameters of the `distribute release` command, so that we don't have to retrieve the release ID after posting it. As it stands, there's a point in time where the build is posted, but no users can download it because the signatures are missing.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
