### ISSUE TITLE
Binary Distribution Randomly Failing

### ISSUE THREAD

**Issue by jpdesjardins-bhvr** [microsoft/appcenter-cli#745]
Hi!

We're using appcenter-cli to upload our binaries to AppCenter in our CI process and every once in a while, we get this kind of error:

```
Release upload failed
Release upload was aborted
Error: release binary uploading failed: socket hang up
```

Our binaries are quite huge, so, that might be a part of the problem, but these errors got more frequent over the past weeks and our binary size didn't change much. Is there anything we can do to alleviate this problem?

Thank you very much!

**Comment by phillipleblanc** [comment]
@jpdesjardins-bhvr - Hey! Thanks for letting us know about this issue. We were doing some work to change the infrastructure around how we process release uploads which might have caused some of the instability you are seeing. Those issues should be fixed by now, so if you are still seeing problems please open a support case by navigating to the App Center portal and clicking the blue chat icon in the bottom right of the screen.

**Comment by jpdesjardins-bhvr** [comment]
Sounds good, thanks for the update!
