### ISSUE TITLE
[feature request] No way to remove release type  ?

### ISSUE THREAD

**Issue by softlion** [microsoft/appcenter-cli#803]
Hi,
i've created an app with a release type.

I want to remove it. I can't find how ?

**Comment by ajaykn** [comment]
Hi @softlion 

Just trying to understand the scenario, do you have a requirement to remove the release_type.

If you want to update the release_type, below command helps
`appcenter apps update -r "Test"`

Let us know if this fits your scenario. 
If not, we can prioritize this accordingly.

**Comment by softlion** [comment]
I've removed it using the web ui.

**Comment by anywherepilot** [comment]
The problem is you can't use the CLI to set it to the custom value "" (nothing, empty string). That is how you do it in the web interface.

**Comment by anywherepilot** [comment]
Because of the way the CLI handles parameters, it cannot distinguish between empty string and the parameter not being provided at all. We have the same problem with booleans: we can't see the difference between false and not provided. That means, short of changing how parameters are dealt with, the only way to make this work is to either take some documented magic value for unsetting the release type, or having a specific parameter for doing so. Let's leave this open and see if it gets any more upvotes or comments.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
