### ISSUE TITLE
Updating notes for existing release

### ISSUE THREAD

**Issue by Vacxe** [microsoft/appcenter-cli#842]
Does it possible to update release notes for existed release?
`appcenter distribute releases edit` looks very close semantically but responsible for different things.

For now, it possible only with `publish` task.

Will be nice to have a possibility to update existed release with new notes file. Could you please add this functionality?

@jp-andre @anywherepilot

**Comment by anywherepilot** [comment]
It should be on that command, I agree. Looks like we currently only have support for enabling and disabling releases. Editing release notes is possible through the API, so it'll be easy to add.

**Comment by Vacxe** [comment]
@anywherepilot can we add `patch` command for example? Because in the opposite case we should modify `update` command what can actually break back compatibility.

Also how far we can receive this feature? Because it's really important for us. Maybe to push this forward could u send me the links for API?

**Comment by anywherepilot** [comment]
`state` should not be required in my opinion. Actually I'm glad you pointed out this parameter, since I have been dealing with some similar "boolean" type parameters recently and I was thinking it makes sense to have this kind of parameter where you need to write "enabled" or "disabled" explicitly. It's good to know we have a precedent.

You can find our API here: https://openapi.appcenter.ms

The one you'd need to work with is the [PUT operation for updating a release](https://openapi.appcenter.ms/#/distribute/releases_updateDetails).

We'll have a look at your PR. Thanks for taking it upon yourself to add this functionality.
