### ISSUE TITLE
appcenter distribute release with "App API Token" Issue

### ISSUE THREAD

**Issue by dan-trewin** [microsoft/appcenter-cli#856]
Hi, I am trying to use the appcenter-cli to release my iOS app in a cicd pipeline.

I got it working using the following command:
```
appcenter distribute release --app MyOrg/MyApp --file ./dist/myApp.ipa --group "My App Alpha Testers" --token XXXXX --silent
```
I was using my own "User API Token" for this command.

I was happy it was so easy to get it working, but I decided I'd rather use an "App API Token" so that the pipeline had less permissions in case anything ever got compromised.

So I ran the same command with my "App API Token".

The command still distributed a version of the app to app center but my distribution group can't see it and the terminal output says it failed: 
```
 Error: Could not add group My App Alpha Testers to release 2
```

Is this a bug in the CLI ?
Or is there a way I can configure an "App API Token" where it won't get this error?

**Comment by hagould** [comment]
I've just tried a similar scenario with the CLI and wasn't able to reproduce this issue, but it's possible that you've run into a different flow. Could you re-run the command with the --debug arg and paste the output (being careful to remove sensitive information) here? Alternatively you can open a support ticket via our main appcenter.ms website to keep any sensitive information out of this public conversation.

**Comment by dan-trewin** [comment]
I used the --debug arg. I removed or replaced pieces with sensitive info.

```
Using appcenter-cli version: 2.5.0
| Loading prerequisites...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/MyOrg/MyApp/distribution_groups/My%20App%20Alpha%20Testers/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.0 NodeJS/v13.13.0 darwin/18.7.0",
    "x-api-token": "XXXXX",
    "internal-request-source": "cli",
    "diagnostic-context": "XXXXX",
    "cli-command-name": "distribute release"
  },
  "body": null
}
- Loading prerequisites...Response status code: 403
Body: {"error":{"code":"Forbidden","message":"You do not have sufficient permission to perform this action on distribution group \"My App Alpha Testers\""}}
| Creating release upload...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/MyOrg/MyApp/release_uploads",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.0 NodeJS/v13.13.0 darwin/18.7.0",
    "x-api-token": "XXXXX",
    "internal-request-source": "cli",
    "diagnostic-context": "XXXXX",
    "cli-command-name": "distribute release"
  },
  "body": null
}
/ Creating release upload...Response status code: 201
Body: {"upload_id":"d599496c-2dd3-421a-bc5c-1b49d8a0ae9b","upload_url":"XXXXX","asset_id":"XXXXX","asset_domain":"https://file.appcenter.ms","asset_token":"XXXXX"}
| Finishing release upload...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/MyOrg/MyApp/release_uploads/d599496c-2dd3-421a-bc5c-1b49d8a0ae9b",
  "method": "PATCH",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.0 NodeJS/v13.13.0 darwin/18.7.0",
    "x-api-token": "XXXXX",
    "internal-request-source": "cli",
    "diagnostic-context": "XXXXX",
    "cli-command-name": "distribute release"
  },
  "body": "{\"status\":\"committed\"}"
}
| Finishing release upload...Response status code: 200
Body: {"release_id":"6","release_url":"v0.1/apps/MyOrg/MyApp/releases/6"}
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/MyOrg/MyApp/distribution_groups/My%20App%20Alpha%20Testers",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.5.0 NodeJS/v13.13.0 darwin/18.7.0",
    "x-api-token": "XXXXX",
    "internal-request-source": "cli",
    "diagnostic-context": "XXXXX",
    "cli-command-name": "distribute release"
  },
  "body": null
}
Response status code: 403
Body: {"error":{"code":"Forbidden","message":"You do not have sufficient permission to perform this action on distribution group \"My App Alpha Testers\""}}
Error: Could not add group My App Alpha Testers to release 6
```

So it seems the "App API Token" has permission to release the app but doesn't have permission to release it to a distribution group for some reason.  Any ideas?

**Comment by hagould** [comment]
Yep - you're running into this because the distribution group is an organization aka shared distribution group. The app token's currently aren't scoped to validate that you have the permissions to distribute to the org group, but it's something that we're currently talking about. 

In the meantime you would be able to perform this action with a distribution group created for this app or with a user token.

**Comment by dan-trewin** [comment]
Ok, thanks for looking!

I will likely just use the user token.

But how would you create a distribution group for this app?

**Comment by hagould** [comment]
I'm referring to creating a distribution group on the app itself, rather than from the 'people' section under an organization. Including an image of the website UI below:

<img width="1542" alt="Screen Shot 2020-05-06 at 12 06 10 PM" src="https://user-images.githubusercontent.com/44214179/81217935-3ecf6d80-8f92-11ea-9182-a746d7b620b7.png">

**Comment by dan-trewin** [comment]
Got it! Thank you for the helpful responses. I will try that solution out. I didn't realize there was a distribution group option "per app" so to speak. Closing the thread!

**Comment by rohan20** [comment]
This behaviour is a little weird. How can I create just one organisation level group and distribute multiple apps to the same group via CLI? 

Is there any other workaround for not having to create the same distribution group and add the same people to those groups across all apps?

**Comment by oliviergauthier** [comment]
You can create Teams and Dristribution Groups at organisation level. You will need to add dedicated user and get his personal Token with write access,

**Comment by slarti-b** [comment]
> Also worth noting that this isn't a bug, and the CLI is working as intended

Personally, I would still count it as bug.  The bug may be in the spec, rather than the code, but it's a bug :)

The CI system is, by definition, not a person so not a specific user.  It _should_ be running using an app token not a user token.  At the same time, having "separate but identical" distribution groups per app for internal testers, etc. is not a god approach either.  Therefore, the logical approach is to allow distribution using an app token to any groups already connected to that app.  I don't see a big security problem here, since you have connected the group to the app already.

(Also, as noted by others here, the user tokens are much more powerful and have a wider impact if leaked)

>  The app token's currently aren't scoped to validate that you have the permissions to distribute to the org group, but it's something that we're currently talking about.

This was a bit over a year ago.  Can you update on how those talks progressed?

**Comment by aleksandr-dorofeev** [comment]
Hi, @slarti-b 
I answered you in a new issue that you opened!
Check, please!
