### ISSUE TITLE
Test Wizard does not ask for the path to test-cloud.exe

### ISSUE THREAD

**Issue by denis-reichelt** [microsoft/appcenter-cli#933]
Just tried the "appcenter test wizard" command on the cli to upload a test manually. The experience was good so far as the wizard gave me chances to specify paths to the app and to the tests. Unfortunately it is not asking for the path to the test-cloud.exe so the process stopped with the error: 
```
Preparing tests... failed.
Error: Cannot find test-cloud.exe, which is required to prepare UI tests.
We have searched for directory "packages\Xamarin.UITest.*\tools" inside "c:\" and all of its parent directories.
Please use option "--uitest-tools-dir" to manually specify location of this tool.
Minimum required version is "2.2.0".
```
Is this test-cloud.exe still needed for UITests?
In the wizard mode I'm not able to give this path as a command line argument so this should be requested from the user when it is not found, shouldn't it?

**Comment by yujincat** [comment]
The wizard is not taking optional parameter `--uitest-tools-dir` assuming the default. That is, the current implementation of wizard does not consider a manually specified path for test-cloud.exe. 

The workaround for this case would be putting `test-cloud.exe` in the default path.
Hope this can answer your question. I labeled this as `Enhancements` so that this can be improved.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
