### ISSUE TITLE
Creating a release through the API - How do I know when the upload status is complete?

### ISSUE THREAD

**Issue by dexterleng** [microsoft/appcenter-cli#945]
The response from the API `POST /v0.1/apps/{owner_name}/{app_name}/builds/{build_id}/distribute` is 

```
{
    "upload_id": "<id>",
    "status": "started"
}
```

Is there an API call I can make with the `upload_id` to get the status of the upload, and when the status is complete I can get the release `id`?

**Comment by anywherepilot** [comment]
This question is not related to the CLI. However, if you are using the API to create a release, you must yourself mark the upload as complete (since you're doing the uploading). See the doc on [releasing through the API](https://docs.microsoft.com/en-us/appcenter/distribution/uploading#distributing-using-the-apis).

The only endpoints we have related to release uploads are the `POST` and `PATCH` ones. There is no `GET` to check the current upload status. Both the CLI and the App Center portal perform the release as a single process, so they keep track of the status in memory, hence we haven't needed it.

You can create a feature request for this endpoint in the [main App Center repository](https://github.com/microsoft/appcenter). Until then, you can try to set up communication between your process which is doing the uploading and the one which wants to know whether that is done.

The CLI `distribute release` command won't complete until the upload is done, or failed.

**Comment by anywherepilot** [comment]
Please feel free to re-open or just comment if that didn't answer your question.
