### ISSUE TITLE
Unable to publish app to appcenter from JenkinsCI running on mac node.

### ISSUE THREAD

**Issue by rhaly** [microsoft/appcenter-cli#977]
Running appcenter login fails with message:

`Error: Could not add password to keychain: security: SecKeychainItemCreateFromContent (<default>): User interaction is not allowed.`

Problem is that appcenter stores token in keychain and Jenkins is connected to mac node over ssh.

**Comment by anywherepilot** [comment]
Hi @rhaly. I'd like to make sure I understand the scenario. You want to communicate with App Center through the CLI from inside a CI job, running with Jenkins. You're trying to perform the operation `appcenter login --token <token>` or `appcenter login --user <user> --password <password>`. This operation fails, with that error about the key chain? The error mentions user interaction. It looks like it means interaction with the key chain. Just to be sure though, you're not just running `appcenter login` without arguments? That would open interactive login mode, which doesn't work in CI because it requires user action.

Since you mention Node, which version of Node is the job running with? The App Center CLI only supports Node version 10.*.

**Comment by rhaly** [comment]
Hi @anywherepilot .
I'm using `appcenter login --token <token>`. I've meant node as Jenkins Node it's other name for agent.
But there is node.js installed on mac agent with version 12.16.3. Everything runs fine when im running `appcenter login --token` from local machine, but fails over ssh.

**Comment by anywherepilot** [comment]
Hi @rhaly. Since the CLI indeed needs access to the key chain to store the password - this is the purpose of `appcenter login` - you will need to have this access. If your user does not have that access, as appears to be the case, then you cannot use `appcenter login`. That doesn't mean you cannot use other `appcenter` commands. You'll just have to use the `token` parameter which each invocation. You could write a little wrapper script to handle this for you, if you can't obtain the required permissions.

**Comment by rhaly** [comment]
That works for me thanks for help.
